### ISSUE TITLE
FileInfo

### ISSUE THREAD

**Issue by kPlusPlus** [ihabunek/pdf417-php#10]
FileInfo is not exists on new PHP systems.
What have to do for changes.

**Comment by ihabunek** [comment]
FileInfo is required by the `intervention/image` library which is used for creating images. 

I've been away from PHP recently, but I'm pretty sure that fileinfo is still available. [The docs](http://php.net/manual/en/fileinfo.installation.php) say it's enabled by default since PHP 5.3.

What system are you running this on?

**Comment by gjuric** [comment]
FileInfo extension is available on PHP 7.1
